### ISSUE TITLE
my20220306: sporadic '---' values displayed for AWS and AWA

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#20] opened 2022-03-07 09:39 UTC
This bug has not yet been analyzed thoroughly, but despite valid values being reveived by the MFD they are not displayed. So far, also no other input values have been checked for this behaviour

**Comment by norbert-walter** [comment] 2022-03-09 18:31
I can't reproduce it

**Comment by W-Geronius** [comment] 2022-03-11 20:26
the bug could not be observed since a change was made to accept lowercase letters in NMEA0183 checksum. Until then, the converter ignored these MWV sentences. If it ignores more than 3-4 sentences (3-4 seconds), the converter assumed a dropout of winddata. From the logs, on rare occasions, I could see 4 consecutive records with lowercase hex.
I suggest to close this issue

**Comment by norbert-walter** [comment] 2022-03-20 14:52
I close it.

**Closed as completed by norbert-walter** 2022-03-20 14:52 UTC
Labels: bug
